name: PentestingPOS-security

services:
  migration:
    pull_policy: never
    build:
      context: .
      target: migrator
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?schema=public
      ADMIN_USERNAME: "admin@wholesale.com"
      ADMIN_PASSWORD: "1234"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - security_net

  db:
    image: postgres:16-alpine
    platform: linux/amd64
    pull_policy: if_not_present
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - security_net

  app:
    build:
      context: .
      target: runner
    image: ${APP_IMAGE_NAME}-security:${APP_IMAGE_TAG}
    pull_policy: never
    container_name: PentestingPOS-app-security
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_LOCALE: ${NEXT_PUBLIC_LOCALE}
    depends_on:
      migration:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://app/login').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))\""]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    networks:
      - security_net

  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    platform: linux/amd64
    container_name: PentestingPOS-zap
    #tty: true                  
    #stdin_open: true

    depends_on:
      app:
        condition: service_healthy

    volumes:
      - ./security/zap-plan-realistic.yaml:/zap/zap-plan-realistic.yaml:ro
      - ./security/reports:/zap/reports:rw
      - ./security/zap-work:/zap/work:rw
      #- ./security/reports:/zap/wrk:rw

    # entrypoint: [""]
    #command: zap-baseline.py -t http://app -d -z "-config spider.maxDuration=0" -r spider-report.html 
    command:
      - zap.sh
      - -cmd
      - -autorun
      - /zap/zap-plan-realistic.yaml

    networks:
      - security_net

    restart: "no"

networks:
  security_net:
    name: PentestingPOS-security-net
    driver: bridge
    internal: true

volumes:
  pgdata:
  zapdata:
