env:
  contexts:
    - name: "Authenticated-App"
      urls:
        - "http://app"
      includePaths:
        - "http://app.*"
      excludePaths:
        - ".*logout.*"
        - ".*signout.*"
        - ".*login.*"
      authentication:
        method: "browser"
        parameters:
          loginPageUrl: "http://app/login"
          loginPageWait: 5
          browserId: "firefox-headless"
        verification:
          method: "response"
          loggedInRegex: '\Q<pos-page-marker>\E'
          loggedOutRegex: '\Q/login\E'
          pollUrl: "http://app/pos"
          pollFrequency: 60
          pollUnits: "requests"
      users:
        - name: "scan_admin"
          credentials:
            username: "admin@wholesale.com"
            password: "1234"

# docker run --rm --network PentestingPOS-security-net curlimages/curl -i \
#   -X POST http://app/api/auth/login \
#   -H "content-type: application/json" \
#   -d '{"email":"admin@wholesale.com","password":"1234"}'

jobs:
  - type: replacer
    parameters: {}
    rules:
      - description: "Inject JWT Bearer token"
        url: "http://app.*"
        matchType: "REQ_HEADER"
        matchString: "Authorization"
        replacementString: "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5Ad2hvbGVzYWxlLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJBZG1pbiIsInJvbGVJZCI6MSwiaWF0IjoxNzg1ODI0MzQ1LCJleHAiOjE3ODU5MTA3NDV9.8vmE6X-RRNFB6iWK63abQVHYBgPrx8Ql8cDBOoX5oNU"
        initiators: []

  # - type: spider
  #   parameters:
  #     context: "Authenticated-App"
  #     user: "scan_admin"
  #     url: "http://app.*"
  #     maxDuration: 5

  - type: spiderAjax
    parameters:
      user: "scan_admin"

  # - type: passiveScan-wait
  #   parameters:
  #     maxDuration: 5

  # - type: activeScan
  #   parameters:
  #     context: "Authenticated-App"
  #     user: "scan_admin"
  #     policy: "Default Policy"
  #     maxRuleDurationInMins: 2
  #     maxScanDurationInMins: 5

  - type: report
    parameters:
      template: "modern"
      reportDir: "/zap/reports"
      reportFile: "zap-authenticated-report"