env:
  contexts:
    - name: POS
      urls:
        - http://app
      includePaths:
        - http://app.*

jobs:
  - type: spider
  - type: passiveScan-wait
  # - type: activeScan
  - type: report

  - type: report
    parameters:
      template: traditional-html
      reportDir: /zap/reports
      reportFile: report.html

  - type: report
    parameters:
      template: traditional-json
      reportDir: /zap/reports
      reportFile: report.json